### ISSUE TITLE
Crouch Vaulting Stucks Player

### ISSUE THREAD

**Issue by LeftoverAtoms** [DevulTj/sbox-fps_sample#1]
Simply crouch then vault into a prefab similar to this.
![saveasda](https://user-images.githubusercontent.com/66341882/209059115-0cac0038-b3bc-4a4a-9aae-c0d80d526f6b.png)

Because vaulting is determined by the current bbox size and crouching reduces it but forces the player to stand after a vault, this causes the player to be stuck within the wall if the hole is less than 72 units tall.

**Comment by LeftoverAtoms** [comment]
Just noticed you had another branch with unstuck I suppose this could still be a valid issue?

**Comment by DevulTj** [comment]
This should be fixed.
